name = "deepseek-graphql-api"
main = "index.js"
compatibility_date = "2024-01-15"

# KV 存储配置
[[kv_namespaces]]
binding = "CHAT_SESSIONS"
id = "80b396c93de04092b9fc4a57b98bfbf3"
preview_id = "e636e4df02b84370b6a949004b38bc1b"

# 环境变量（敏感信息通过 wrangler secret 设置）
[vars]
NODE_ENV = "production"

# 本地开发环境变量
[env.development.vars]
NODE_ENV = "development"
# 在本地开发时，可以在这里设置 DEEPSEEK_API_KEY
# DEEPSEEK_API_KEY = "your-api-key-here"

# 或者创建 .dev.vars 文件来存储本地环境变量

# 路由配置（可选）
# routes = [
#   { pattern = "api.yourdomain.com/graphql", zone_name = "yourdomain.com" }
# ]

# 兼容性标志
compatibility_flags = ["nodejs_compat"]